language: node_js
node_js:
  - "10.4.1"
sudo: true


branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
- ng build --prod
deploy:
  provider: heroku
  api_key:
    secure: d00921bf-092c-4da1-afb8-8c638d9191ad
  app: ausecourseappli
