language: node_js
node_js:
  - "10.4.1"
sudo: true


branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
- ng build --prod --base-href https://Oreta.github.io/testIntegration/
